## Initial inspection of Data and EDA

In [4]:
import numpy as np
import pandas as pd

In [35]:
df=pd.read_csv("../data/raw/ball_by_ball_data.csv")
df

,season_id,match_id,batter,bowler,non_striker,team_batting,team_bowling,over_number,ball_number,batter_runs,...,is_bye,is_penalty,wide_ball_runs,no_ball_runs,leg_bye_runs,bye_runs,penalty_runs,wicket_kind,is_super_over,innings
0,2008,335982,SC Ganguly,P Kumar,BB McCullum,6,1,0,0,0,...,False,False,0,0,1,0,0,NaN,False,1
1,2008,335982,BB McCullum,P Kumar,SC Ganguly,6,1,0,1,0,...,False,False,0,0,0,0,0,NaN,False,1
2,2008,335982,BB McCullum,P Kumar,SC Ganguly,6,1,0,2,0,...,False,False,1,0,0,0,0,NaN,False,1
3,2008,335982,BB McCullum,P Kumar,SC Ganguly,6,1,0,3,0,...,False,False,0,0,0,0,0,NaN,False,1
4,2008,335982,BB McCullum,P Kumar,SC Ganguly,6,1,0,4,0,...,False,False,0,0,0,0,0,NaN,False,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
288221,2026,1529286,T Stubbs,JC Archer,Ashutosh Sharma,252,134,18,3,1,...,False,False,0,0,0,0,0,NaN,False,2
288222,2026,1529286,Ashutosh Sharma,JC Archer,T Stubbs,252,134,18,4,1,...,False,False,0,0,0,0,0,NaN,False,2
288223,2026,1529286,T Stubbs,JC Archer,Ashutosh Sharma,252,134,18,5,4,...,False,False,0,0,0,0,0,NaN,False,2
288224,2026,1529286,Ashutosh Sharma,Brijesh Sharma,T Stubbs,252,134,19,0,4,...,False,False,0,0,0,0,0,NaN,False,2
288225,2026,1529286,Ashutosh Sharma,Brijesh Sharma,T Stubbs,252,134,19,1,0,...,False,False,0,1,0,0,0,NaN,False,2

In [21]:
### Every match id is unique and ball by ball data is given for each innings
df[df["season_id"]==2008]

,season_id,match_id,batter,bowler,non_striker,team_batting,team_bowling,over_number,ball_number,batter_runs,...,is_bye,is_penalty,wide_ball_runs,no_ball_runs,leg_bye_runs,bye_runs,penalty_runs,wicket_kind,is_super_over,innings
0,2008,335982,SC Ganguly,P Kumar,BB McCullum,6,1,0,0,0,...,False,False,0,0,1,0,0,NaN,False,1
1,2008,335982,BB McCullum,P Kumar,SC Ganguly,6,1,0,1,0,...,False,False,0,0,0,0,0,NaN,False,1
2,2008,335982,BB McCullum,P Kumar,SC Ganguly,6,1,0,2,0,...,False,False,1,0,0,0,0,NaN,False,1
3,2008,335982,BB McCullum,P Kumar,SC Ganguly,6,1,0,3,0,...,False,False,0,0,0,0,0,NaN,False,1
4,2008,335982,BB McCullum,P Kumar,SC Ganguly,6,1,0,4,0,...,False,False,0,0,0,0,0,NaN,False,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141603,2008,336040,SK Warne,L Balaji,Sohail Tanvir,134,129,19,2,1,...,False,False,0,0,0,0,0,NaN,False,2
141604,2008,336040,Sohail Tanvir,L Balaji,SK Warne,134,129,19,3,0,...,False,False,2,0,0,0,0,NaN,False,2
141605,2008,336040,SK Warne,L Balaji,Sohail Tanvir,134,129,19,4,1,...,False,False,0,0,0,0,0,NaN,False,2
141606,2008,336040,Sohail Tanvir,L Balaji,SK Warne,134,129,19,5,2,...,False,False,0,0,0,0,0,NaN,False,2
141607,2008,336040,Sohail Tanvir,L Balaji,SK Warne,134,129,19,6,1,...,False,False,0,0,0,0,0,NaN,False,2

In [36]:
df.isnull().sum()

season_id                 0
match_id                  0
batter                    0
bowler                    0
non_striker               0
team_batting              0
team_bowling              0
over_number               0
ball_number               0
batter_runs               0
extras                    0
total_runs                0
batsman_type            239
bowler_type             339
player_out           273886
fielders_involved    273886
is_wicket                 0
is_wide_ball              0
is_no_ball                0
is_leg_bye                0
is_bye                    0
is_penalty                0
wide_ball_runs            0
no_ball_runs              0
leg_bye_runs              0
bye_runs                  0
penalty_runs              0
wicket_kind          273886
is_super_over             0
innings                   0
dtype: int64

In [39]:
df2=pd.read_csv("../data/raw/ipl_matches_data.csv")
df2

,match_id,season_id,balls_per_over,city,match_date,event_name,match_number,gender,match_type,format,...,venue,toss_winner,team1,team2,toss_decision,match_winner,win_by_runs,win_by_wickets,result,player_of_match
0,335982,2008,6,Bangalore,2008-04-18,Indian Premier League,1.0,male,T20,T20,...,M Chinnaswamy Stadium,1,1,6,field,6,140.0,NaN,win,46.0
1,1082591,2017,6,Hyderabad,2017-04-05,Indian Premier League,1.0,male,T20,T20,...,"Rajiv Gandhi International Stadium, Uppal",1,2,1,field,2,35.0,NaN,win,15.0
2,1082592,2017,6,Pune,2017-04-06,Indian Premier League,2.0,male,T20,T20,...,Maharashtra Cricket Association Stadium,4,4,3,field,4,NaN,7.0,win,36.0
3,1082593,2017,6,Rajkot,2017-04-07,Indian Premier League,3.0,male,T20,T20,...,Saurashtra Cricket Association Stadium,6,5,6,field,6,NaN,10.0,win,57.0
4,1082594,2017,6,Indore,2017-04-08,Indian Premier League,4.0,male,T20,T20,...,Holkar Cricket Stadium,494,494,4,field,494,NaN,6.0,win,71.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1207,1529282,2026,6,Delhi,2026-04-27,Indian Premier League,39.0,male,T20,T20,...,"Arun Jaitley Stadium, Delhi",1,252,1,field,1,NaN,9.0,win,4664.0
1208,1529283,2026,6,New Chandigarh,2026-04-28,Indian Premier League,40.0,male,T20,T20,...,Maharaja Yadavindra Singh International Cricke...,134,494,134,field,134,NaN,6.0,win,11389.0
1209,1529284,2026,6,Mumbai,2026-04-29,Indian Premier League,41.0,male,T20,T20,...,"Wankhede Stadium, Mumbai",3,3,2,bat,2,NaN,6.0,win,1740.0
1210,1529285,2026,6,Ahmedabad,2026-04-30,Indian Premier League,42.0,male,T20,T20,...,"Narendra Modi Stadium, Ahmedabad",615,1,615,field,615,NaN,4.0,win,4098.0
1211,1529286,2026,6,Jaipur,2026-05-01,Indian Premier League,43.0,male,T20,T20,...,"Sawai Mansingh Stadium, Jaipur",134,134,252,bat,252,NaN,7.0,win,1409.0

Some columns like gender(since ipl has only males in it), format and some more irrelevant columns can be skipped.

In [33]:
df2=df2.sort_values("season_id")
df2["season_id"].value_counts().sort_index()

## Columns contain data for all years, it just wasn't sorted, so we sort it

season_id
2008    58
2009    57
2010    60
2011    73
2012    74
2013    76
2014    60
2015    59
2016    60
2017    59
2018    60
2019    60
2020    60
2021    60
2022    74
2023    74
2024    71
2025    74
2026    43
Name: count, dtype: int64

In [37]:
df2.isnull().sum()

match_id             0
season_id            0
balls_per_over       0
city                51
match_date           0
event_name           0
match_number        70
gender               0
match_type           0
format               0
overs                0
season               0
team_type            0
venue                0
toss_winner          0
team1                0
team2                0
toss_decision        0
match_winner         0
win_by_runs        666
win_by_wickets     571
result               0
player_of_match      9
dtype: int64

# Approach considered
A new dataset can be constructed by adding and combining the wickets, total runs and more from ball by ball dataset for each innings. We also need the team aliases dcoument to map team ids to their respective team names

In [42]:
df3=pd.read_csv("../data/raw/team_aliases.csv")
df3

    alias_id  team_id                   alias_name
0          1        1                          RCB
1          2        1  Royal Challengers Bengaluru
2          3      252             Delhi Daredevils
3          4      494              Kings XI Punjab
4          5        1  Royal Challengers Bangalore
5          6        1                     Banglore
6          7        1                    Bengaluru
7          8      252               Delhi Capitals
8          9      252                           DC
9         10      252                           DD
10        11      252                        Delhi
11        12      494                 Punjab Kings
12        13      494                         KXIP
13        14      494                       Punjab
14        15        2          Sunrisers Hyderabad
15        16        2                          SRH
16        17        2                    Hyderabad
17        18        2              Deccan Chargers
18        19        3               Mumbai Indians
19        20        3                           MI
20        21        3                       Mumbai
21        22        4       Rising Pune Supergiant
22        23        4      Rising Pune Supergiants
23        24        4                          RPS
24        25        4                         Pune
25        26        5                Gujarat Lions
26        27        5                           GL
27        28        6        Kolkata Knight Riders
28        29        6                          KKR
29        30        6                     Kolkatta
30        31      129          Chennai Super Kings
31        32      129                          CSK
32        33      129                      Chennai
33        34      134             Rajasthan Royals
34        35      134                    Rajasthan
35        36      134                           RR
36        37      614         Lucknow Super Giants
37        38      614                          LSG
38        39      614                      Lucknow
39        40      615               Gujarat Titans
40        41      615                           GT
41        42     1414         Kochi Tuskers Kerala
42        43     1414                          KTK
43        44     1414                       Kerala
44        45     1419                Pune Warriors
45        46     1419                          PWI

We will have to map current, playing team names to their team ids and replace them in the original dataset in the preprocessing part